Update master_mywebappr2p.yml

diff --git a/.github/workflows/master_mywebappr2p.yml b/.github/workflows/master_mywebappr2p.yml
--- a/.github/workflows/master_mywebappr2p.yml
+++ b/.github/workflows/master_mywebappr2p.yml
@@ -14,6 +14,7 @@ jobs:
     runs-on: ubuntu-latest
     permissions:
       contents: read #This is required for actions/checkout
+      id-token: write #This is required for requesting the JWT
 
     steps:
       - uses: actions/checkout@v4
@@ -23,39 +24,17 @@ jobs:
         with:
           node-version: '20.x'
 
-      - name: npm install, build, and test
+      - name: Install dependencies and build
+        working-directory: /home/runner/work/ecommerce-app/ecommerce-app
         run: |
           npm install
-          npm run build --if-present
-          npm run test --if-present
-
-      - name: Zip artifact for deployment
-        run: zip release.zip ./* -r
-
-      - name: Upload artifact for deployment job
-        uses: actions/upload-artifact@v4
-        with:
-          name: node-app
-          path: release.zip
-
-  deploy:
-    runs-on: ubuntu-latest
-    needs: build
-    environment:
-      name: 'Production'
-      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
-    permissions:
-      id-token: write #This is required for requesting the JWT
-      contents: read #This is required for actions/checkout
-
-    steps:
-      - name: Download artifact from build job
-        uses: actions/download-artifact@v4
-        with:
-          name: node-app
-
-      - name: Unzip artifact for deployment
-        run: unzip release.zip
+          npm run build:prod
+  
+      - name: Verify build output
+        working-directory: /home/runner/work/ecommerce-app/ecommerce-app
+        run: |
+          if [ -d "./dist/ecommerce-app" ]; then echo "Build directory exists."; else echo "Build failed!"; exit 1; fi
+          ls ./dist/ecommerce-app
       
       - name: Login to Azure
         uses: azure/login@v2
@@ -70,5 +49,5 @@ jobs:
         with:
           app-name: 'mywebappr2p'
           slot-name: 'Production'
-          package: .
+          package: /home/runner/work/ecommerce-app/ecommerce-app/dist/ecommerce-app
           
